add button solution
js-tasks-ru/htmlcss-20211021_kazakevich-j pull request #3
Opened 2021-10-30 12:19 UTC by kazakevich-julia

Сверстала только те кнопки, которые были в описании задания (состояние hover не верстала, т. к. не знала, нужно ли было). Расположение тоже как в задании (в строку), но если нужно, переделаю как в макете (друг под другом). Спасибо!

2021-10-30 12:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-01 15:13 UTC, GSemikozov requested changes

2021-11-01 15:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
font-family все-таки лучше указать явно, поскольку наследоваться можем от любого родителя, соответственно, там могут использоваться разные шрифты

2021-11-01 15:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_secondary {
не хватет еще одного. типа - .btn_alternate

2021-11-01 15:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn_secondary {
точнее, оно = default состоянию, но - это будет не правильно, специфический тип кнопки лучше оформить отдельно)

2021-11-03 20:13 UTC, GSemikozov approved these changes

2021-11-03 20:13 UTC, merged