add accordion solution
js-tasks-ru/htmlcss-20211021_kazakevich-j pull request #4
Opened 2021-10-30 14:17 UTC by kazakevich-julia

2021-10-30 14:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-01 15:16 UTC, GSemikozov requested changes

2021-11-01 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +* {
1-9 строчки - это общие сбросы стилей, их надо вынести либо в reset.css либо в main.css

2021-11-01 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin: 32px;
кстати, на body луччше не задавать марджины, их наоборот сбрасывают

2021-11-01 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
марджины на уровне блока не задаем, можно .accordion сделать общим враппером, у которого нынешних accordion. превратится в .accordion__item, и вот уже элемену блока можно будет задать марджины

2021-11-01 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__hidden-content {
можно просто .accordion__content

2021-11-02 16:04 UTC, kazakevich-julia commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
спасибо за комментарии. задала общий враппер и марджины элементам. на самой странице блок accordion никак не располагала, так как не совсем ясно, нужно ли это делать для отдельного элемента. мы же его будем встраивать? поправьте меня, пожалуйста, если я не правильно поняла

2021-11-05 19:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-17 18:19 UTC, GSemikozov approved these changes

2021-11-17 18:19 UTC, merged